### ISSUE TITLE
system.unhandledexceptionseventards

### ISSUE THREAD

**Issue by kyhftaeonn** [qwe5283/SkyPC_AutoMusic#1]
[Enchanted.txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/14230420/Enchanted.txt)
its cant open a sheet like this. it says system.unhandledexceptionseventards
anyways, may i translate this application? ofcourse i'll add the credit just only tou. i just want to easier using this application using english language

**Comment by qwe5283** [comment]
I've tried to fix it in the latest release

**Comment by qwe5283** [comment]
I've added English option in the latest release

**Comment by kyhftaeonn** [comment]
nice work! thanksieee. gonna try

**Comment by kyhftaeonn** [comment]
anyways, i have a good suggestion for next update. thats to add search tool for sheet selection. thats a good feature though

**Comment by qwe5283** [comment]
search tool finished
