### ISSUE TITLE
Failure in music importation

### ISSUE THREAD

**Issue by Electric-Cat** [qwe5283/SkyPC_AutoMusic#2]
![image](https://github.com/qwe5283/SkyPC_AutoMusic/assets/60434386/24a1b5ba-ff84-4be9-bed1-4c7d2ed8152f)

I don't know if it's something I did wrong or if the program can't import the songs. I tried to import just one song and it gave me this error, and when I try to import a folder with songs, it goes into an infinite loop.

It's my first time using any auto music program for Sky, but I know that it's possible to download .txt music files. However, I'm not sure if these problems are related to something I did wrong or if it's an issue with the program itself.

**Comment by qwe5283** [comment]
please provide the music file that caused the program exception

**Comment by Electric-Cat** [comment]
[Gravity_Fall_Opening_Theme_Song.txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15144831/Gravity_Fall_Opening_Theme_Song.txt)
[Faded_Iceman.txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15144832/Faded_Iceman.txt)

This is the first time I've looked for something like this, so I can't say if I really did something wrong.

**Comment by triemnguyen123** [comment]
I also got the same error when importing more than 4 songs, the above error started to occur
![image](https://github.com/qwe5283/SkyPC_AutoMusic/assets/107350813/d15873c2-44e1-4144-af47-3d37072f5b4e)
Error song: 
[Porter_Robson__Madeon_-_Shelter.txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15146090/Porter_Robson__Madeon_-_Shelter.txt)
[Nandemonaiya.txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15146092/Nandemonaiya.txt)

**Comment by qwe5283** [comment]
looks like your song files are not made with Sky Studio, I'll try to support this kind of files. check it in the latest release?

**Comment by Electric-Cat** [comment]
![image](https://github.com/qwe5283/SkyPC_AutoMusic/assets/60434386/55332e12-bcc1-43aa-bd6f-90f839b738ff)
"The operation was not completed successfully because the file contains a virus or
potentially unwanted software."

This message appeared when I started the new version.

**Comment by Electric-Cat** [comment]
![image](https://github.com/qwe5283/SkyPC_AutoMusic/assets/60434386/5ffb95ee-4b3a-401c-b48c-2639bdcdb6e2)
![image](https://github.com/qwe5283/SkyPC_AutoMusic/assets/60434386/d0a1ad70-7fc9-4b0d-9938-aee31bd92ebe)

**Comment by qwe5283** [comment]
Windows Defender usually blocks almost every program it doesn't recognize. but this program is safe and you can add it to the white list

**Comment by Electric-Cat** [comment]
Now it works perfectly! thanks <3
