### ISSUE TITLE
使用2.1以上版本无法添加曲谱，只有2.1版本可以添加

### ISSUE THREAD

**Issue by 2015505068** [qwe5283/SkyPC_AutoMusic#3]
使用2.1以上版本无法添加曲谱，只有2.1版本可以添加，试了很多次都不可以
![1](https://github.com/qwe5283/SkyPC_AutoMusic/assets/97935701/9f0f45d7-0ac9-40e2-a2a9-207006c23bc1)
![2](https://github.com/qwe5283/SkyPC_AutoMusic/assets/97935701/095d1549-6f2a-4ae5-a7ac-c6fb1a8eb143)

**Comment by qwe5283** [comment]
把无法被添加的乐谱文件发一下

**Comment by 2015505068** [comment]
我感觉是因为太多了，导致没法识别了
![1](https://github.com/qwe5283/SkyPC_AutoMusic/assets/97935701/9f38745e-38bc-45fc-b437-e627b0ff20fc)
这些是随便选了几个
抱歉我不知道为什么上传不了txt😭

**Comment by 2015505068** [comment]
[Uploading co chac yeu la ay Cvtin.txt…]()

**Comment by 2015505068** [comment]
![CTC Can](https://github.com/qwe5283/SkyPC_AutoMusic/assets/97935701/4ddc159e-70de-42b7-8338-2914a9d5950e)

**Comment by qwe5283** [comment]
没txt文件我很难定位问题啊😂

**Comment by 2015505068** [comment]
[1Chihara Minori - Michishirube (みちしるべ) OST Violet Evergarden (by Noaaru).txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15213421/1Chihara.Minori.-.Michishirube.OST.Violet.Evergarden.by.Noaaru.txt)
[1FIFTY FIFTY - Cupid (short easy ver.) (by aeWonnielicious).txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15213422/1FIFTY.FIFTY.-.Cupid.short.easy.ver.by.aeWonnielicious.txt)
[Wn, Duongg, Nâu - 3107 3.txt](https://github.com/qwe5283/SkyPC_AutoMusic/files/15213423/Wn.Duongg.Nau.-.3107.3.txt)
我随便选了几个，因为谱子太多了，希望能帮上忙

**Comment by qwe5283** [comment]
看了一下，你发的三个谱子中有两个是加密的所以软件不能识别😂这与版本新旧无关

**Comment by 2015505068** [comment]
可是其他的也不可以，那么多都不行，只能用前几个曲子，后面的都用不了，2.1版本缺可以

**Comment by qwe5283** [comment]
你试试用“从文件夹中导入”按钮选择你存放那2000多个乐谱的文件夹，会不会导入途中进度突然停下然后无休止导入？

**Comment by 2015505068** [comment]
是的！一直无休止的导入！卡在30之后一直不动！
![2](https://github.com/qwe5283/SkyPC_AutoMusic/assets/97935701/37904c8e-17c0-45a8-a790-72787878f205)

**Comment by qwe5283** [comment]
试着修了一下，你试试？

**Comment by 2015505068** [comment]
![1](https://github.com/qwe5283/SkyPC_AutoMusic/assets/97935701/3ae8ac4e-d758-4077-8df6-02d7ad9e4028)
还是不可以😭

**Comment by qwe5283** [comment]
用刚刚发布的2.1.5还是不行嘛？

**Comment by 2015505068** [comment]
是的，2.1.5也不可以😭

**Comment by qwe5283** [comment]
方便发一下你的所有txt乐谱文件以便追踪问题吗🧐如果这里不方便，压缩一下添加附件发邮箱到w1074479225@163.com也行😣

**Comment by 2015505068** [comment]
好的！我发你邮箱

**Comment by qwe5283** [comment]
已经修好了

**Comment by 2015505068** [comment]
辛苦大佬了！

**Comment by Khoipham24** [comment]
how to use?

**Comment by Gremio1** [comment]
why is the button not working properly?
为什么按钮无法正常工作？

**Comment by Gremio1** [comment]
why does all the music get deleted when I close the app. am I supposed to add music every time I launch the app? 
为什么我关闭应用后，所有音乐都会被删除？难道我每次启动应用都要添加音乐吗？

**Comment by qwe5283** [comment]
> how to use?

This application doesn't provide any music so you need to gather sheet music files manually

**Comment by achuanzaici** [comment]
现在的新版版不支持txt版本了嘛
